version: '2'
services:
  db:
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=liam
        - POSTGRES_PASSWORD=123
      ports:
        - '5432:5432'
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql